### PR TITLE
Typo in documentation: warning box

### PR DESCRIPTION
**Pull request by gnowland**
"box notice" should be "box warning" for warning boxes

### CODE REVIEW

**Comment by alexandresaiz** [comment]
@gnowland should you update css file too?
https://github.com/MONEI/Shopify-Embedded-App-Frontend-Framework/blob/master/css/seaff.css

**Comment by gnowland** [comment]
@alexandresaiz nope, it's good to go.

**Comment by alexandresaiz** [comment]
alright. then, one, two, three... go!

**Comment by alexandresaiz** [comment]
btw, can you help in any of the pending issuess?

https://github.com/MONEI/Shopify-Embedded-App-Frontend-Framework/issues

**Comment by gnowland** [comment]
Looks like you just need to git pull on http://seaff.microapps.com/, the doc hasn't updated yet :)

**Comment by alexandresaiz** [comment]
@gnowland done!

**Comment by gnowland** [comment]
@alexandresaiz good deal! 

I'll take a look at those issues as soon as I have a moment!

**Pull request merged**
